//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int id { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string Number { get; set; }
        public string KullaniciTipi { get; set; }
    }
}
